### ISSUE TITLE
URL links of "Deploy to Azure" buttons are not referencing the V2 repo

### ISSUE THREAD

**Issue by tewfikm** [F5Networks/f5-azure-arm-templates-v2#1]
## Describe the bug

For both payg and big-iq V2 variants, Url links of 'Deploy to Azure' Buttons are generating following error message within Azure Portal :

There was an error downloading the template from URI 'https://raw.githubusercontent.com/F5Networks/f5-azure-arm-templates/v1.0.0.0/examples/autoscale/payg/azuredeploy.json'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint. To deploy this template, download the template manually and paste the contents in the 'Build your own template in the editor' option below. 

 
## Expected behavior
 
PAYG template URL link should reference the V2 repo as the below :
https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FF5Networks%2Ff5-azure-arm-templates-V2%2Fv1.0.0.0%2Fexamples%2Fautoscale%2Fpayg%2Fazuredeploy.json
 
## Current behavior
 
Payg template URL link is referencing :

https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FF5Networks%2Ff5-azure-arm-templates%2Fv1.0.0.0%2Fexamples%2Fautoscale%2Fpayg%2Fazuredeploy.json
 
## Possible solution

workaround : Import JSON using Templates in Azure portal

**Comment by mikeshimkus** [comment]
Created internal issue 2259 to fix the broken links; thanks for reporting.

**Comment by shyawnkarim** [comment]
Closing.

This issue was resolved with [Release 1.1](https://github.com/F5Networks/f5-azure-arm-templates-v2/releases/tag/v1.1.0.0).
