### ISSUE TITLE
License regkey parameter missing for BYOL license type

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-azure-arm-templates-v2#10]
### Is your feature request related to a problem?

PAYG versus BYOL licensing
 
### Describe the solution you'd like
 
User wants to deploy BYOL license type. Current example does not ask for a license regkey. There is nothing in runtime init example yaml files for a rendered regkey. The example yaml files have hard coded reg keys of AAAAA-BBBBB-CCCCC-DDDDD-EEEE.

**Comment by JeffGiroux** [comment]
similar to AWS templates https://github.com/F5Networks/f5-aws-cloudformation-v2/issues/13

**Comment by shyawnkarim** [comment]
Closing.

Our team discussed this idea and the consensus was not to add this since it would create more management overhead/clutter. Additionally, the README does cover how to modify a template.
