### ISSUE TITLE
Failover always be deployed into AvailabilityZone 1

### ISSUE THREAD

**Issue by TomTomDE** [F5Networks/f5-azure-arm-templates-v2#18]
## Describe the bug
 
If we deploy Failover Template, with or without Existing Stack. Both Failover Instances are deployed into Availability Zone 1 if useAvailabilityZones is set to true (bool)

## Expected behavior
 
if useAvailabilityZones is set to true Availability Zones should be used and the 2 virtual Machines should be stretched accross multiple Zones like 1 and 2, 2 and 3 or 1 and 3
 
## Current behavior

if useAvailabilityZones is set to true, both VMs deployed on Availability Zone 1 
 
## Possible solution / problem location

Code-Line in examples/modules/bigip-standalone/bigip.json
"zones": "[if(parameters('useAvailabilityZones'), createArray(1), json('null'))]",
createArray(1) << this set the used Zone always to 1

## Idea
let Zones be defined in ARM Template Deployment as Variable ... like Zone VM1 = 1, Zone VM2 = 2

**Comment by mikeshimkus** [comment]
Hi @TomTomDE, thanks for reporting. This was fixed with internal issue #3136, which will be included in the next release.

**Comment by TomTomDE** [comment]
thanks, working

**Comment by shyawnkarim** [comment]
Closing.

This issue was resolved with [Release 2.4.0.0](https://github.com/F5Networks/f5-azure-arm-templates-v2/releases/tag/v2.4.0.0).
