### ISSUE TITLE
bigIpPeerAddr - documentation inaccuracy

### ISSUE THREAD

**Issue by de1chk1nd** [F5Networks/f5-azure-arm-templates-v2#19]
## Documentation link
 

https://github.com/F5Networks/f5-azure-arm-templates-v2/tree/main/examples/failover
 
## Describe the problem
bigIpPeerAddr - without some kind of reverse engineering it is not 100% clear which IP is expected (IP from first device, as trust is established from second bigip).
Yes - looking at IP and reverse engineer does the trick; looking at runtime-init and see trust is established from second device does the trick, too. but it would be better to have it in the docs - stating IP of first memeber is expected (sync initiated from second member). 

 
inaccuracy

see above
 
## Suggested fix
 

see above

**Comment by f5-applebaum** [comment]
Thank you for submitting feedback. We will update the descriptions to make this clearer. Tracking internally w/ issue #3159.

**Comment by shyawnkarim** [comment]
Closing. Our documentation was updated, for all three clouds, with [Release 2.5.0.0](https://github.com/F5Networks/f5-azure-arm-templates-v2/releases/tag/v2.5.0.0).
