### ISSUE TITLE
Deployment Failed due to Parent resource not found

### ISSUE THREAD

**Issue by danielcayer** [F5Networks/f5-azure-arm-templates-v2#20]
## Describe the bug
 
Deployment fails because the bigIpPasswordSecretId is not found within the resource group which the ARM template creates.
 
## Expected behavior
 
The deployment should allow the bigIpPasswordSecretId to be in a pre-existing resource group. 
 
## Current behavior
 
Deployment fails in the accessTemplate resource with the following Operation Detail:
{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
            {
                "code": "NotFound",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"ParentResourceNotFound\",\r\n    \"message\": \"Can not perform requested operation on nested resource. Parent resource 'cayerkeyvault' not found.\"\r\n  }\r\n}"
            }
        ]
    }
}

Within the child accessTemplate, the Operation Detail of the corresponding failed resource deployment is as follows: 
{
    "status": "Failed",
    "error": {
        "code": "ParentResourceNotFound",
        "message": "Can not perform requested operation on nested resource. Parent resource 'cayerkeyvault' not found."
    }
}

## Possible solution
 
Comments under issue #16 indicate that this issue should have been resolved in this version of the ARM template (v2.4.0.0)???
 
## Steps to reproduce
 
1. create a bigip password secrect
2. deploy via the "new stack" button found at this location: https://github.com/F5Networks/f5-azure-arm-templates-v2/tree/main/examples/failover#deploying-via-the-azure-deploy-button
3. provide all required input for the ARM template and click to create in Azure
4. wait for the deployment to fail
 
 
## Context
 
I cannot use this template to create a new stack.
 
## Your Environment
 
tried to deploy to Canada Central and to Canada East regions with same failed result.
 
- Version used: 4.2.0.0
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): n/a
- Operating System and version (desktop or mobile): n/a
- Link to your project: n/a

**Comment by mikeshimkus** [comment]
Hi @danielcayer, when creating the deployment, did you also supply a pre-existing user assigned managed identity (as documented here: https://github.com/F5Networks/f5-azure-arm-templates-v2/tree/main/examples/failover#prerequisites)?

**Comment by danielcayer** [comment]
Ah! Thank you Mike!

I missed that pre-requisite for the user assigned managed identity because the README indicates that it is optional and that it will be created automatically if one is not provided.


Sincères salutations,

Daniel Cayer
+1-613-868-1535<tel:+1-613-868-1535>  |  ***@***.******@***.***>

From: Mike Shimkus ***@***.***>
Date: Wednesday, September 21, 2022 at 10:20 PM
To: F5Networks/f5-azure-arm-templates-v2 ***@***.***>
Cc: Daniel Cayer ***@***.***>, Mention ***@***.***>
Subject: Re: [F5Networks/f5-azure-arm-templates-v2] Deployment Failed due to Parent resource not found (Issue #20)

Hi @danielcayer<https://github.com/danielcayer>, when creating the deployment, did you also supply a pre-existing user assigned managed identity (as documented here: https://github.com/F5Networks/f5-azure-arm-templates-v2/tree/main/examples/failover#prerequisites)?

**Comment by shyawnkarim** [comment]
Closing. Please open another issue if needed.
