### ISSUE TITLE
Microsoft.Support provider error

### ISSUE THREAD

**Issue by DahlPatric** [F5Networks/f5-azure-arm-templates-v2#26]
## Describe the bug
 

When trying to deploy template in Azure China we receive below error. 
```
{
    "status": "Failed",
    "error": {
        "code": "InvalidActionOrNotAction",
        "message": "The resource provider referenced in the action 'Microsoft.Support/*' is not returned in the list of providers from Azure Resource Manager."
    }
}
```

While investing further Provider Microsoft.Support seams not exist.
**az provider list --query "[?namespace=='Microsoft.Support']" --output table** 

No result from above command.

**az provider list --query "[?registrationState=='Registered']" --output table**
No registrated

**az provider list --query "[?registrationState=='NotRegistered']" --output table**
Does not exist in result.

 
## Expected behavior
 

Script should install a complete set of F5:devices
 
## Current behavior
 
Script fail and no F5´s deployed.

**Comment by DahlPatric** [comment]
Hi! @mikeshimkus, Fork git for a new deployment and removed Microsoft.Support as last time this was successful.
But now to my surprise error message shows up even if value is removed. 

New-AzResourceGroupDeployment : 13:44:12 - The deployment 'F5-HA-Deploy' failed with error(s). Showing 2 out of 2 error(s).
Status Message: The resource provider referenced in the action 'Microsoft.Support/*' is not returned in the list of providers from Azure Resource Manager. (Code:InvalidActionOrNotAction)
Status Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details. (Code: DeploymentFailed)

{
  "error": {
    "code": "InvalidActionOrNotAction",
    "message": "The resource provider referenced in the action 'Microsoft.Support/*' is not returned in the list of providers from Azure Resource Manager."
  }

**Comment by mikeshimkus** [comment]
Hi @DahlPatric, are you sure your parent template is still pointing to the modified version of the access template? If you drill down into the deployments tab of your resource group, and find the template that was used, you should be able to verify that the provider was still removed.

**Comment by DahlPatric** [comment]
Hi mikeshimkus! Thanks for pointing me into right directions, totally forgot this from previous time.

**Comment by DahlPatric** [comment]
Closing case.
