### ISSUE TITLE
Command failed: /usr/bin/setdb restjavad.useextramb true Cannot set db variable (restjavad.useextramb = true)

### ISSUE THREAD

**Issue by renaranj** [F5Networks/f5-azure-arm-templates-v2#29]
## Documentation link
 

Version 16.1.4.1 is not fully validated.
https://github.com/F5Networks/f5-azure-arm-templates-v2/tree/main/examples/failover#big-ip-versions

During the deployment you get the next error:
Command failed: /usr/bin/setdb restjavad.useextramb true Cannot set db variable (restjavad.useextramb = true)

that error arise because that variable "restjavad.useextramb" is not available on version 16.1.4.1 anymore.

According to the runtime init Doc,  16.1.4.1 is not validated, instead the version 16.1.3.3, which indeed support that variable.
https://github.com/F5Networks/f5-bigip-runtime-init?search=1#validated-big-ip-versions

**Comment by mikeshimkus** [comment]
Hi @renaranj, which template did you use? Were you using the most recent version? These were tested against 16.1.4 prior to release.

**Comment by renaranj** [comment]
Thanks for the reply. I found the Template for existing stack bring the runtime unit config v2.0 Yaml script per default. I edit it to match the 3.0 . After that, the issues was over.

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>



Ronald Enrique Naranjo Paredes
Security Consultant SOC

***@***.***


CANCOM Managed Services GmbH
Poßmoorweg 2
22301 Hamburg
Germany


Phone    +49 40 227443-2039
Mobile   +49 160 6158147

***@***.******@***.***>
https://www.cancom.de

***@***.***<https://de.linkedin.com/company/cancom> ***@***.*** <https://www.instagram.com/cancom.se/>  ***@***.*** <https://twitter.com/cancom_se>  ***@***.*** <https://www.facebook.com/CANCOM/>  ***@***.*** <https://www.youtube.com/c/cancom>  ***@***.*** <https://www.xing.com/company/cancom>


CANCOM Managed Services GmbH
Sitz der Gesellschaft: München
HRB 249726 München
Geschäftsführer: Rüdiger Rath, Thomas Stark


Diese E-Mail und alle mit gesendeten Dateien sind vertraulich und ausschließlich für den Gebrauch durch den Empfänger bestimmt!
This e-mail and any files transmitted with it are confidential intended solely for the use of the addressee!

***@***.***
<http://www.cancom.info>



<http://www.cancom.com/Presse/Pressemitteilungen/tabid/158/controlToLoad/ViewNote/noteId/469/language/de-DE/Default.aspx>

________________________________
Von: Mike Shimkus ***@***.***>
Gesendet: Monday, January 8, 2024 4:00:15 PM
An: F5Networks/f5-azure-arm-templates-v2 ***@***.***>
Cc: Ronald Enrique Naranjo Paredes ***@***.***>; Mention ***@***.***>
Betreff: Re: [F5Networks/f5-azure-arm-templates-v2] Command failed: /usr/bin/setdb restjavad.useextramb true Cannot set db variable (restjavad.useextramb = true) (Issue #29)


Hi @renaranj<https://github.com/renaranj>, which template did you use? Were you using the most recent version? These were tested against 16.1.4 prior to release.
