### ISSUE TITLE
can we get a standalone example with an easy deploy button?

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/f5-azure-arm-templates-v2#32]
### Is your feature request related to a problem?
 
My problem is that some customers want to deploy a standalone BIG-IP and the v2 templates are too hard to fork and customize for non-experts. However, those excellent examples with simple "Deploy to Azure" buttons are easy for me to direct a customer to. 

I only want a standalone BIG-IP, but the quickstart example uses nested templates and a demo app. Can I get an example with a single ARM template for a standalone BIG-IP?
  
### Describe the solution you'd like
 
An easy standalone BIG-IP deployment. With or without bigip-runtime-init config. Just something to easily deploy a standalone BIG-IP. 
 
### Describe alternatives you've considered

Right now I have a customer deploying a failover pair and then manually deleting one of them 😄 
 
### Additional context
 
I know that moving from v1 to v2 templates made some things easier, but most customers I've talked to just don't understand v2 and will often just use deprecated v1 templates. Forking, customizing, nesting templates and using base url's are too much to walk the average person through, but those easy examples make it possible to show customers v2 templates working quickly.

**Comment by mikeshimkus** [comment]
Hi @mikeoleary, you can do that by using the standalone bigip template by itself: https://github.com/F5Networks/f5-azure-arm-templates-v2/tree/main/examples/modules/bigip-standalone. There are only 4-6 required parameters (how many depends on how many NICs you want).

Would need to reverse engineer the deploy button link, e.g.: https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FF5Networks%2Ff5-azure-arm-templates-v2%2Fv3.0.0.0%2Fexamples%2Fmodules%2Fbigip-standalone%2Fbigip.json

**Comment by mikeoleary** [comment]
Hi @mikeshimkus,

I've done this, so I admit it sounds silly, but can we make it an example that customers can do this just by clicking on an example, all through the GUI?

What I really want is something dead-simple for a customer to deploy right from the GUI, without having to download a json template, edit files, know the bigipruntimeInit file to point at, etc.

Is that something others have asked for?

**Comment by mikeoleary** [comment]
Happy to close this one due to development priorities.
