### ISSUE TITLE
Is there a plan for bicep templates?

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/f5-azure-arm-templates-v2#41]
### Is your feature request related to a problem?
 
No. I have a customer wondering if bicep supported templates are planned or on the roadmap.
 
### Describe the solution you'd like
 
Bicep support.
 
### Describe alternatives you've considered
 
I am talking to the team about alternative, but supported deployment methods (ARM template, Terraform module, GUI, etc)

**Comment by f5jason** [comment]
I have a customer who has standardized on Bicep for all of their Azure deployments. This would make F5 BIG-IP VE deployments ridiculously easy for them.

**Comment by mikeshimkus** [comment]
Hi @f5jason @mikeoleary ATM, we have no plans to create Bicep templates for BIG-IP VE. Please follow up with me directly if you have more questions.

**Comment by mikeoleary** [comment]
thank you for the update @mikeshimkus
