### ISSUE TITLE
Unable to upgrade autoscaling BIG-IP instances from 15.1.x to 16.0.1

### ISSUE THREAD

**Issue by laul7klau** [F5Networks/f5-azure-arm-templates-v2#7]
## Describe the bug
This is based on the deployment template in 
https://github.com/F5Networks/f5-azure-arm-templates-v2/blob/master/examples/autoscale/payg/README.md
After successful deployment to 
f5-networks:f5-big-ip-best:f5-bigip-virtual-edition-25m-best-hourly:15.1.200000
followed the steps in the Readme.md and unable to upgrade to
f5-networks:f5-big-ip-best:f5-bigip-virtual-edition-25m-best-hourly:16.0.101000 

100% repro

## Expected behavior
Upgrade to 16.0.1 should work. 
Tested upgrading to 
f5-networks:f5-big-ip-best:f5-bigip-virtual-edition-25m-best-hourly:15.1.201000
and it works.

Tested with the following: 
Standard_DS2_v2, Standard_DS3_v2, Standard_DS4_v2
US East, East 2, West, West 2
Use Availability Zones: False ( shouldn't matter)

 
## Current behavior
Deployment failed with any of the following error:
"properties": {
        "statusMessage": "{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"ResizeDiskError\",\"message\":\"The disk/snapshot resource with id https://md-bhgcxr10md3t.blob.core.windows.net/z0v42cbnh3m2/abcd cannot be resized down. Reducing disk/snapshot size is not supported in Azure to prevent data loss. If you do need to reduce the size of the disk, please create new snapshot/disks with the appropriate size. More information is available at https://aka.ms/AzureDisksFAQ.  Target: '/subscriptions/6e07f378-7faa-4648-8ec8-9cbeff6c2342/resourceGroups/D5instance1512West2/providers/Microsoft.Compute/disks/d5instance1512west2-d5instance1512west2-vOS__1_9cb7d5912d7d40078e2a91a54b8ed3ef'.\"}]}}",

OR 

{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
            {
                "code": "Conflict",
                "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"MaxUnhealthyUpgradedInstancePercentExceededInRollingUpgrade\",\r\n        \"message\": \"Rolling Upgrade failed after exceeding the MaxUnhealthyUpgradedInstancePercent value defined in the RollingUpgradePolicy. 100% of instances are in an unhealthy state after being upgraded - more than the threshold of 20%. The most impactful error is: The disk/snapshot resource with id https://md-vvhzngb24hlr.z34.blob.storage.azure.net/c544kxx0tch0/abcd cannot be resized down. Reducing disk/snapshot size is not supported in Azure to prevent data loss. If you do need to reduce the size of the disk, please create new snapshot/disks with the appropriate size. More information is available at https://aka.ms/AzureDisksFAQ.  Target: '/subscriptions/6e07f378-7faa-4648-8ec8-9cbeff6c2342/resourceGroups/DS5EAST/providers/Microsoft.Compute/disks/ds5east-vmss_ds5east-vmss_0_OsDisk_1_5720d2a48073411e86e396133d4da273'.. First failed instance ID is: 0.\"\r\n      }\r\n    ]\r\n  }\r\n}"
            }
        ]
    }
}
 
## Possible solution
- Looks like the size of bigip 16.0.1 is smaller than 15.1.x giving rise to the error.
- For the normal Azure Machine, this value could be edited "diskSizeGB": 78 but for auto scaling, could be related to https://docs.microsoft.com/en-us/azure/automation/automation-runbook-gallery
- And referring to the "Scale Down Virtual Machine Scale Set Instances" Runbook here -> 
https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-vertical-scale-reprovision
-- may be able to use to Runbook there?
-- The Runbook appears to state Standard_DS2_v2, Standard_DS3_v2, Standard_DS4_v2 are able to support 'resize'
 
## Steps to reproduce
https://github.com/F5Networks/f5-azure-arm-templates-v2/blob/master/examples/autoscale/payg/README.md
100% repro with the following:
1. First deploy 15.1.2.0 
   a. Click "Deploy to Azure" 
   b. Use all default values. Set Use Availability Zone: False
After successful deployment, upgrade to 16.0.1
2. Upgrade
   a. Go to the resource group. 
   b. Select Deployments
   c. Select the original deployment. E.g. Microsoft.Template-<date> 
   d. Redploy
   e. Edit Template
   f. Replace 15.1.200000 -> 16.0.101000
   g. Save
   h. Set Use Availability Zone: False.
   i. Agree and Purchase

BIG-IP instances are untouched but deployment returns error listed above.

## Context
After successfully deploying 15.1.x, try to upgrade to 16.0.1

**Comment by shyawnkarim** [comment]
Thanks for reporting this. We are now tracking it internally with ID ESECLDTPLT-2643.

**Comment by shyawnkarim** [comment]
Closing.

This bug fix was included with [Release 1.4.0.0](https://github.com/F5Networks/f5-azure-arm-templates-v2/releases/tag/v1.4.0.0).
