### ISSUE TITLE
Quickstart suggests SSH2 format for sshKey parameter

### ISSUE THREAD

**Issue by adityoari** [F5Networks/f5-azure-arm-templates-v2#8]
## Documentation link
 
https://github.com/F5Networks/f5-azure-arm-templates-v2/blob/main/examples/quickstart/README.md
 
## Describe the problem
 
README for Quickstart example suggests to use SSH2 format (BEGIN SSH2 PUBLIC KEY) for the **sshKey** parameter, even though testing and closer looks at the `bigip-standalone` module are both suggesting that OpenSSH format (ssh-rsa ..) is expected. 

From `examples/modules/bigip-standalone/bigip.json`, line 433:
```
                "linuxConfiguration": {
                    "disablePasswordAuthentication": true,
                    "ssh": {
                        "publicKeys": [
                            {
                                "keyData": "[parameters('sshKey')]",
                                "path": "[concat('/home/', parameters('adminUsername'), '/.ssh/authorized_keys')]"
                            }
                        ]
                    }
                }
```

When SSH2-formatted, multi-lines key is used for **sshKey** parameter, the linked `bigipTemplate` deployment would fail with `InvalidParameter` error.
 
## Suggested fix
 
* Remove the incorrect SSH2 format suggestion in the **Description** column of the **sshKey** row, in **Template Input Parameters** table:

  typically starting with ---- BEGIN SSH2 PUBLIC KEY ---- and ending with ---- END SSH2 PUBLIC KEY ----.

* Optionally, add the expected OpenSSH format for clarity:

  typically starting with ssh-rsa.

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue with our documentation. We are now tracking this work internally with ID ESECLDTPLT-2888.
